// <auto-generated />
namespace WebApplication2_with_NTTFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addNewTableFootball : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNewTableFootball));
        
        string IMigrationMetadata.Id
        {
            get { return "202201160859566_addNewTableFootball"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
